#!/usr/bin/env bash
# Deploy the demo-mode bot + its Mini App bundle to the production droplet.
#
# Canonical runbook: ../deploy.md → "Deploy Demo Mode". Design: ../DEMO_MODE.md
#
# This is a SECOND deployment of the same source tree, into its own directory,
# with its own .env (own bot token, own database, own port). Running it is what
# keeps the demo in step with production — same code, same Mini App, one extra
# command per release.
#
# Run it AFTER the production deploy has been verified.
#
# Usage:
#   ./scripts/deploy-demo.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER="root@167.172.178.229"
REMOTE_PATH="/opt/gennety-demo"
WEBAPP_PATH="/var/www/demo-app/"
DEMO_API_BASE="https://demo-api.gennety.com"

cd "$REPO_ROOT"

# ── Isolation gate ─────────────────────────────────────────────────────────
#
# `assertDemoIsolation()` (apps/bot/src/demo/config.ts) cannot check any of
# this: from inside the demo process, production's values are unknowable, so it
# is limited to settings that are wrong on their face (founder notifications on,
# Stars on, an admin key present). This script is the ONLY vantage point where
# both .env files are readable at once — so this is where "did demo inherit a
# production secret?" has to be answered.
#
# It is not hypothetical. `/opt/gennety-demo/.env` is generated by hand as
# production's .env plus the overrides in .env.demo, so every key .env.demo
# forgets is silently inherited. That mechanism leaked SUPABASE_URL on day one
# (caught, deploy.md 2026-08-06) and JWT_SECRET for three days after it (caught
# by audit 2026-08-08, not by anything automatic): both deployments signed and
# accepted the same tokens, with the same hardcoded issuer and audience, while
# `requireAuth` verifies a signature and never looks the user up.
#
# Cheap, and it runs before anything is touched, so a violation costs nothing.
echo "→ Checking demo↔production secret isolation…"
if ! ssh "$SERVER" 'python3 -' <<'ISOLATION'
import hashlib, sys

def load(path):
    values = {}
    try:
        with open(path, encoding="utf-8", errors="replace") as handle:
            for line in handle:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                values[key.strip()] = value.strip().strip('"').strip("'")
    except FileNotFoundError:
        print("  MISSING: %s" % path)
        sys.exit(1)
    return values

prod = load("/opt/gennety/.env")
demo = load("/opt/gennety-demo/.env")

# Sharing any of these means demo traffic can reach production users, data or
# money — or that a demo-side disclosure hands over a production credential.
MUST_DIFFER = [
    "BOT_TOKEN",              # one token = one poller; they would steal updates
    "DATABASE_URL",           # real users
    "SUPABASE_URL",           # real media (bucket names alone are not isolation)
    "SUPABASE_SERVICE_ROLE_KEY",
    "JWT_SECRET",             # a demo-minted /v1/* token would verify on prod
]
# Present in demo at all = a route into production's ops surface.
MUST_BE_ABSENT = ["ADMIN_API_KEY", "FOUNDER_BOT_TOKEN", "FOUNDER_TELEGRAM_ID"]

problems = []
for key in MUST_DIFFER:
    p, d = prod.get(key), demo.get(key)
    if p and d and p == d:
        digest = hashlib.sha256(p.encode()).hexdigest()[:12]
        problems.append("%s is IDENTICAL in both (sha256 %s…)" % (key, digest))
    elif not d:
        problems.append("%s is missing from the demo .env — it inherits production's" % key)
for key in MUST_BE_ABSENT:
    if demo.get(key):
        problems.append("%s must be empty/absent in the demo .env" % key)

if problems:
    print("\n  Demo is NOT isolated from production. Refusing to deploy:")
    for problem in problems:
        print("    - %s" % problem)
    print("\n  Fix /opt/gennety-demo/.env (and .env.demo, so it cannot come back),")
    print("  then re-run. See DEMO_MODE.md → The isolation invariant.\n")
    sys.exit(1)

print("  OK — bot, database, storage and JWT secret are all demo-owned.")
ISOLATION
then
  echo "✗ Isolation check failed — nothing was deployed." >&2
  exit 1
fi

echo "→ Dry-run rsync (every line below is a file that WOULD be deleted)…"
# Same exclude list as production. `.env*` covers the demo's own .env and its
# .bak rollback snapshots; `keys/` holds server-only Apple secrets. Both would
# otherwise be destroyed by --delete.
RSYNC_EXCLUDES=(
  --exclude '.git/'
  --exclude 'node_modules/'
  --exclude 'dist/'
  --exclude 'tmp/'
  --exclude '.env*'
  --exclude 'keys/'
  --exclude '*-backup-*.json'
  --exclude 'prod-backup-*.json'
  --exclude '*.bak.*'
  --exclude '.claude/'
  --exclude '.agents/'
  --exclude '.codex/'
  --exclude '.gstack/'
)
rsync -az --delete --dry-run --itemize-changes "${RSYNC_EXCLUDES[@]}" \
  ./ "$SERVER:$REMOTE_PATH/" | grep '^\*deleting' || echo "   (nothing to delete)"

# Braces are load-bearing where a variable abuts a non-ASCII character: bash
# swallowed the "…" into the identifier and `set -u` killed the script with
# "REMOTE_PATH<mojibake>: unbound variable".
echo "→ Syncing source to ${SERVER}:${REMOTE_PATH}…"
rsync -az --delete "${RSYNC_EXCLUDES[@]}" ./ "$SERVER:$REMOTE_PATH/"

echo "→ Installing, generating Prisma client, building…"
ssh "$SERVER" "cd $REMOTE_PATH && pnpm install --frozen-lockfile && pnpm --filter @gennety/db db:generate && pnpm build"

# The demo runs the same Prisma schema against its own database, so a schema
# change has to be pushed to BOTH. `db:drift-check` is the gate: a demo database
# missing a column throws P2022 at runtime, which surfaces as a PM2 crash loop
# rather than a clean error.
echo "→ Pushing schema to the demo database and checking for drift…"
ssh "$SERVER" "cd $REMOTE_PATH && export DATABASE_URL=\"\$(sed -n 's/^DATABASE_URL=//p' .env | tail -1 | tr -d '\"')\" && pnpm --filter @gennety/db db:push && pnpm db:drift-check"

echo "→ Restarting the demo process…"
ssh "$SERVER" "cd $REMOTE_PATH && pm2 restart gennety-demo --update-env && pm2 save"

# The Mini App bakes its API base at build time (apps/webapp/src/api.ts), so the
# demo needs its own build pointed at the demo API. Same source, same components
# — a visual change ships to both from one checkout.
echo "→ Building the demo Mini App bundle (API base: $DEMO_API_BASE)…"
VITE_API_BASE_URL="$DEMO_API_BASE" pnpm --filter @gennety/webapp build

echo "→ Syncing the Mini App bundle to ${SERVER}:${WEBAPP_PATH}…"
rsync -avz --delete apps/webapp/dist/ "$SERVER:$WEBAPP_PATH"

# Leave the working tree's dist/ matching PRODUCTION, so a later
# ./scripts/deploy-webapp.sh run can never ship a demo-pointed bundle to the
# real Mini App host if someone skips its build step.
echo "→ Rebuilding dist/ back to the production API base…"
pnpm --filter @gennety/webapp build

echo
echo "→ Done. Smoke tests:"
echo "   ssh $SERVER 'pm2 logs gennety-demo --lines 40 --nostream'"
echo "   curl -s $DEMO_API_BASE/v1/ping"
echo "   curl -sI https://demo-app.gennety.com/onboarding.html | head -1"
echo "   # The first log lines must carry the DEMO MODE banner naming the"
echo "   # demo bot and the demo database. If they name production — stop."
